"""Create ROC comparison plot for DL and ML baselines from saved curve data."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import auc, roc_curve


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot ROC comparison chart")
    parser.add_argument(
        "--curve-data",
        type=Path,
        default=Path("outputs/curve_data.json"),
        help="Path to curve_data.json generated by pipeline",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("outputs/roc_comparison_presentation.png"),
        help="Output ROC plot path",
    )
    parser.add_argument(
        "--title",
        type=str,
        default="ROC Curve: Deep Learning vs ML Baselines",
        help="Figure title",
    )
    return parser.parse_args()


def load_curve_data(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(
            f"Curve data file not found: {path}. Run `python main.py` first to generate outputs/curve_data.json."
        )
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def plot_roc(curve_data: dict, output_path: Path, title: str) -> None:
    plt.figure(figsize=(8, 6))

    for model_name, payload in curve_data.items():
        y_true = np.asarray(payload["y_true"], dtype=int)
        y_score = np.asarray(payload["y_score"], dtype=float)

        fpr, tpr, _ = roc_curve(y_true, y_score)
        roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, linewidth=2, label=f"{model_name} (AUC={roc_auc:.4f})")

    plt.plot([0, 1], [0, 1], "k--", linewidth=1, label="Random classifier")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title(title)
    plt.legend(loc="lower right")
    plt.grid(alpha=0.3)
    plt.tight_layout()

    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=160)
    plt.close()


def main() -> None:
    args = parse_args()
    curve_data = load_curve_data(args.curve_data)
    plot_roc(curve_data, args.output, args.title)
    print(f"Saved ROC comparison to: {args.output}")


if __name__ == "__main__":
    main()
